# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS - PROYECTO MUEBLES
# ==========================================

# 1. Nombre de la aplicación
spring.application.name=tienda

# 2. Dirección de la base de datos (Asegúrate de crear 'muebles_db' en pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/muebles_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# 3. Estrategia de creación de tablas (Agilidad)
# 'update' creará las tablas automáticamente basadas en tus clases Java
spring.jpa.hibernate.ddl-auto=update

# 4. Dialecto para hablar el idioma de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Visualización de consultas (Para aprender cómo Java habla con la BD)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

